Updated schema_dumper to include the sequences in dump.final instead of appending it to the passed in stream.
After upgrading to Rails 4.2.X & doing all the associated gem upgrades, we were no longer able to run bin/rake db:schema:dump because we got this error:

```
NoMethodError: private method `puts' called for nil:NilClass
…/gems/pg_sequencer-8bbafc5bbc23/lib/pg_sequencer/schema_dumper.rb:28:in `sequences'
```

After some digging, I was able to determine that that schema_plus_core’s schema_dumper no longer passes around the stream like it used to, and appending to `@dump.final` seemed like the simplest way to recreate the old schema dump file, which always just had the pg_sequencer sequences at the very end.